### ISSUE TITLE
Question about how you define androidextras

### ISSUE THREAD

**Issue by Light-Wizzard** [Skycoder42/QtService#11]
Update: This issue only appears if using Qt Online Installer, I am on Arch Linux Manjaro, once I uninstalled it, I did a full Qt pacman install and rebooted, this issue went away. 

Note I had another issue with the Qt Online Installer having a different compiler signature, and I did try to uninstall and reinstall, and checked permissions, but the Offical Repos work fine, and no issues like this.

I am not developing for Android currently, but my computer is set up for it, my interest in this project is to see if I can use it for QtHttpServer, which is currently a [QtLabs](https://github.com/qt-labs/qthttpserver) project slated for Qt, but I am having a hard time getting started with the example for the EchoService, this is not related to my issue, but it stops me from compiling the project since I do not have androidextras installed on my Desktop, but I could on my Android device, if you get my meaning, I get a lot of warnings, but I only get them for two of the three projects, and I think its due to the way you define them in QT += androidextras, for example:

```
In service.pro
android: QT += androidextras
In android.pro
QT += service androidextras
In AndroidServiceTest.pro
QT += quick service androidextras
```
If I change them as such the compile error and warnings go away:

```
In android.pro
QT               += service
android: QT += androidextras

In AndroidServiceTest.pro
QT              += quick service
android: QT += androidextras
```
Maybe you can look at this, this fix got rid of all the warnings, and now it compiles without errors, the logic is clear enough, only an Android device can use androidextras, so I am sure my fix is correct.

Thanks, Flesh

**Comment by Skycoder42** [comment]
That's a strange error... This should not happen, as the android service backend and the example are excluded in their parent projects for any platform but android.

The `android: QT += androidextras` in `service.pro` is required, as otherwise the plugin will not work on android (Qt does not automatically resolve plugin dependencies, and since this is the default for android, the library needs it)

I assume it's an error with QtCreator configuration maybe? I will keep the issue open for now, but unless I get more informationon this, don't expect it to be resolved. I for myself could not reproduce it yet.

**Comment by Light-Wizzard** [comment]
This error can be reproduced using Arch Linux or Manjaro using Qt Online Installer, and its because qmake gets confused due to them being out of sync, different compiler versions more than likely, but there is already a bug report at Qt regarding that issue, and this goes deep, on Manjaro if I try to build the Online Version, it fails for the same reason, so its an endless loop, and I thought DLL hell was bad, compiler version is even worse.

The Fix was to uninstall Qt Online Installation, and install using Pacman.

Flesh
