### ISSUE TITLE
Passing startup params

### ISSUE THREAD

**Issue by arietto** [Skycoder42/QtService#3]
Hello! I pass custom params via `sc create myservice binPath= ...`
I find that args in main during debug (which is OK). But args from `QCoreApplication` instance contains only app name in `onStart()` handler. So, QtService mutates args. What is the workaround?
I always need to pass some user params during startup to child QProcess instance with `onStart` slot.
BTW, standard backend mode does not eat `args`. At least, windows backend mode mutates `args`.

**Comment by Skycoder42** [comment]
Generally speaking, a service should not depend or any arguments, as each platform handles those differently (as you just experienced yourself). Sometimes they are set, sometimes they arent.

For the windows backend, the service makes use of the arguments that are passed to the *serviceMain*, not the normal *main* (See [windowsservicebackend.cpp](https://github.com/Skycoder42/QtService/blob/master/src/plugins/servicebackends/windows/windowsservicebackend.cpp#L206)). You should propably set those instead of the normal arguments. Refer to the windows documentation on how to do that.

Alternatively, you can always just store the `argc` and `argc` params manually in the actual `main` function of your application and access them independently of the server backend. However, you might find special arguments (like the backend, terminal, etc.) there besides your normal arguments.

**Comment by arietto** [comment]
OK, thank you. I'll use INI file.
